package com.inventory.echostar.inventory.main;

/**
 * Created by stas.savinov on 11/22/2016.
 */

import android.util.Log;

import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.runners.MockitoJUnitRunner;

import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class MainPresenterTest
{
    @Mock
    private MainView view;

    @Mock
    private MainPresenter presenter;

    @Before
    public void setUp() throws Exception
    {
        presenter = new MainPresenter(view);
    }

    @Test
    public void checkCameraPermission() throws Exception
    {
        // This activity does not have any particular business logic,
        // so no tests can be generated by me for now.
    }
}
